import { z } from "zod";

export const TokenKOLResponseSchema = z.object({
  id: z.number(),
  address: z.string(),
  token_address: z.string(),
  symbol: z.string(),
  name: z.string(),
  decimals: z.number(),
  logo: z.string().nullable(),
  price_change_6h: z.string(),
  is_show_alert: z.boolean(),
  is_honeypot: z.boolean().nullable()
});

export const TradeKOLResponseSchema = z.object({
  id: z.number(),
  kolId: z.number(),
  tokenId: z.number(),
  balance: z.string(),
  usd_value: z.string(),
  realized_profit_30d: z.string(),
  realized_profit: z.string(),
  realized_pnl: z.string(),
  realized_pnl_30d: z.string(),
  unrealized_profit: z.string(),
  unrealized_pnl: z.string(),
  total_profit: z.string(),
  total_profit_pnl: z.string(),
  avg_cost: z.string(),
  avg_sold: z.string(),
  buy_30d: z.number(),
  sell_30d: z.number(),
  sells: z.number(),
  price: z.string(),
  cost: z.string(),
  position_percent: z.string(),
  last_active_timestamp: z.number(),
  history_sold_income: z.string(),
  history_bought_cost: z.string(),
  start_holding_at: z.number().nullable(),
  end_holding_at: z.number().nullable(),
  liquidity: z.string(),
  wallet_token_tags: z.array(z.string()).nullable(),
  token: TokenKOLResponseSchema
});

export const KOLResponsechema = z.object({
  id: z.number(),
  twitter_bind: z.boolean(),
  twitter_url: z.string().url(),
  twitter_fans_num: z.number(),
  twitter_username: z.string(),
  twitter_name: z.string(),
  ens: z.string().nullable(),
  avatar: z.string().url(),
  name: z.string(),
  balance: z.string(),
  total_value: z.number(),
  unrealized_profit: z.number(),
  unrealized_pnl: z.number(),
  realized_profit: z.number(),
  pnl: z.number(),
  pnl_1d: z.number(),
  pnl_7d: z.number(),
  pnl_30d: z.number(),
  realized_profit_1d: z.number(),
  realized_profit_7d: z.number(),
  realized_profit_30d: z.number(),
  winrate: z.number(),
  all_pnl: z.number(),
  total_profit: z.number(),
  total_profit_pnl: z.number(),
  buy_1d: z.number(),
  sell_1d: z.number(),
  buy_7d: z.number(),
  sell_7d: z.number(),
  buy_30d: z.number(),
  sell_30d: z.number(),
  buy: z.number(),
  sell: z.number(),
  history_bought_cost: z.number(),
  token_avg_cost: z.number(),
  token_sold_avg_profit: z.number().nullable(),
  token_num: z.number(),
  profit_num: z.number(),
  pnl_lt_minus_dot5_num: z.number(),
  pnl_minus_dot5_0x_num: z.number(),
  pnl_lt_2x_num: z.number(),
  pnl_2x_5x_num: z.number(),
  pnl_gt_5x_num: z.number(),
  last_active_timestamp: z.number(),
  tags: z.array(z.string()),
  tag_rank: z.record(z.string(), z.number().nullable()),
  followers_count: z.number(),
  is_contract: z.boolean(),
  updated_at: z.number(),
  refresh_requested_at: z.number().nullable(),
  avg_holding_peroid: z.number(),
  trades: z.array(TradeKOLResponseSchema)
});

export type KOLResponse = z.infer<typeof KOLResponsechema>;